controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Existing controllers
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gripper_controller:
      type: position_controllers/JointGroupPositionController

gripper_controller:
  ros__parameters:
    joints:
      - Slider 22
      - Slider 23
